# 后端 Dockerfile
# 使用 node:20 作为基础镜像

# 从 Docker Hub 拉取 node:20 镜像作为基础镜像
FROM node:20

# 设置工作目录，后续命令都在这个目录下执行
WORKDIR /app

# 复制所有文件到工作目录
COPY . .

# 安装项目依赖
RUN npm install

# 暴露 3000 端口
# 这个命令只是声明容器会使用 3000 端口，实际的端口映射在 docker-compose.yml 中配置
EXPOSE 3000

# 启动后端服务
# 先生成 Prisma 客户端，然后使用 node index.js 命令启动服务
CMD ["sh", "-c", "node_modules/.bin/prisma generate && node index.js"]
